# Generated by Django 4.2 on 2023-04-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rubric',
            new_name='MenuItem',
        ),
    ]
