# Generated by Django 4.2 on 2023-04-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_rename_rubric_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
