# Generated by Django 4.2 on 2023-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_menuitem_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='custom_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
